# Generated by Django 3.0.2 on 2020-01-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputData', models.TextField()),
                ('outputData', models.TextField()),
            ],
        ),
    ]
