# Generated by Django 3.0.3 on 2020-05-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_content_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='language',
            field=models.CharField(choices=[('c', 'C'), ('python', 'Python')], default='python', max_length=10),
        ),
    ]
