# Generated by Django 3.0.7 on 2020-06-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200524_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='language',
            field=models.CharField(choices=[('c', 'C'), ('c++', 'C++'), ('python', 'Python')], default='python', max_length=10),
        ),
    ]
